### ISSUE TITLE
Can't load images

### ISSUE THREAD

**Issue by Rubylion** [mhoeher/opentodolist#8] opened 2018-06-04 07:38 UTC
Hi. I'm on Android LineageOS 14.1. When I try to add an image, it opens the android storage manager. I can browse to my images, but they are grayed out and not selectable. Storage permissions are all set. Regards

**Comment by mhoeher** [comment] 2018-06-04 10:55
Hi @Rubylion,

sorry to hear that adding images is not working for you. I created an issue over on GitLab.com to track this: https://gitlab.com/rpdev/opentodolist/issues/203

I have no device with LineageOS set up, but I'll see what I can do to reproduce and fix the issue. ;-)

**Comment by Rubylion** [comment] 2018-06-05 01:15
thanx

**Comment by mhoeher** [comment] 2020-01-03 20:32
First of all: Sorry for coming back on this one that late. But better now than never...

After I was not quite successful at reproducing the issue, I notices the same issue on my device (Pixel 3). I tracked the problem down to two "bugs":

- First, there was a real bug in the code (probably due to some refactoring work earlier), which caused the app to try to use the generic file picker on Android (which currently does not work and hence is not enabled).
- Additionally, I think the app has to explicitly request certain permissions at runtime - in our case, access to files and media.

I fixed both on the current master branch (over on GitLab). The fixes will be part of the next release (which should be available soon, if I manage to, in the course of the next weekend).

**Closed by mhoeher** 2020-01-03 20:32 UTC
