### ISSUE TITLE
Absolute gibberish in the Windows 10 App

### ISSUE THREAD

**Issue by brimwats** [mhoeher/opentodolist#27] opened 2020-11-17 09:02 UTC
I just downloaded the Windows 10 64bit and it's...confusing

![image](https://user-images.githubusercontent.com/49103046/99368867-8eabbd00-2870-11eb-9441-e478b25c5e23.png)
![image](https://user-images.githubusercontent.com/49103046/99368870-8fdcea00-2870-11eb-9836-ad3b31d81857.png)
![image](https://user-images.githubusercontent.com/49103046/99368873-910e1700-2870-11eb-85ea-c63a1e7136a5.png)

**Comment by mhoeher** [comment] 2020-11-17 09:39
Hm... interesting. I saw this kind of behaviour when using the app inside a Virtual Machine with 3D acceleration enabled. Are you by chance in such a scenario?

If not, I am afraid this could be some artifacts due to rendering. Could you please provide some details about your system, e.g. do you have integrated graphics or a dedicated graphics card? Also, does restarting the app help? Note that it is not enough to close the window - the app continues to run in the background. You will have to right click the app icon in the system tray and explicitly tell it to exit).

**Comment by mhoeher** [comment] 2020-12-08 21:00
Closing due to no further feedback received... if you still can reproduce the issue, please reopen and let me know.

**Closed by mhoeher** 2020-12-08 21:00 UTC
